spring.application.name=gestao-UFC
# Conexão com o banco PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.fgeuewmcmzsifryjworo
spring.datasource.password=Pazzinofera2
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Paginação padrão
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100